app/main/forms.py
"""
Notes Web App
Copyright (C) 2019 DesmondTan
"""


###########
# Imports #
###########

from flask_wtf import FlaskForm
from flask_pagedown.fields import PageDownField
from wtforms.fields.html5 import EmailField
from wtforms import StringField, PasswordField, SubmitField, RadioField, SelectField
from wtforms.validators import required, equal_to, length, ValidationError
from wtforms.validators import Email

from app.models import User


################
# Form Classes #
################

class AddNoteForm(FlaskForm):
    """Add Note Form"""
    private_radio_style = {
        'style': 'list-style: none; margin: 0; padding: 0;'
    }

    title = StringField('Note Title:', [required("Please enter a note title.")])
    note = PageDownField('Your Note:', [required('Please enter notes contents.')])
    # tags = SelectMultipleField('Note Tags:')
    private = RadioField('Private:', choices=[('on', 'on'), ('off', 'off')], render_kw=private_radio_style)
    folder = SelectField('Folder:', choices=[('0', 'All')], default='0')
    submit = SubmitField('Add Note')


class SearchForm(FlaskForm):
    """Search notes and users form"""
    choices = [
        ('Users', 'Users'),
        ('Notes', 'Notes')
    ]

    search = StringField("Search Note/Users", [required("Unable to search empty string.")])
    category = SelectField('Category', choices=choices, default='Notes')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
"""
Notes Web App
Copyright (C) 2019 DesmondTan
"""


###########
# Imports #
###########

from . import main

from flask import (
    request, render_template, redirect, session, flash, url_for, abort
)

from .forms import AddNoteForm, SearchForm

from ..utils.decorators import login_required
from ..utils.functions import *


#########
# Views #
#########

@main.route('/')
def index():
    """Home Page"""
    try:
        if session['username']:
            return render_template('main/index.html', username=session['username'])
        return render_template('main/index.html', username=None)
    except (KeyError, ValueError):
        return render_template('main/index.html', username=None)


@main.route('/today')
@login_required
def today():
    """
    Today Page:
    Displays all the notifications like the word of the day, news highlights or friends who added you or shared a
    note with you
    """

    return render_template('main/today.html', username=session['username'])


@main.route('/home')
@login_required
def home_page():
    """
    Home Page:
    Displays all the notes that other people has shared in the form of a card
    """

    return render_template('main/home_page.html', username=session['username'])


@main.route('/my_notes', methods=['GET', 'POST'])
@login_required
def my_notes():
    """Notes Page"""

    search_form = SearchForm()

    if search_form.validate_on_submit():
        search = request.form['search']
        category = request.form['category']
        return redirect(url_for('main.search_results', search=search, category=category))

    notes = get_notes(session['user_id'])
    usernames = get_usernames()
    folders = get_folder_names_ids(session['user_id'])
    notes_sorted_by_folders = sort_notes_into_folders(notes, folders)
    folder_names = sorted(notes_sorted_by_folders.keys())

    return render_template(
        'main/my_notes.html',
        form=search_form,
        usernames=usernames,
        folder_names=folder_names,
        notes=notes_sorted_by_folders,
        username=session['username']
    )


@main.route('/search_results/?search=<search>&category=<category>')
@login_required
def search_results(search, category):
    """Search results Page"""

    search_form = SearchForm()

    results = get_search_result(search, category, session['user_id'])
    usernames = get_usernames()

    return render_template('main/search_results.html',
                           form=search_form,
                           results=results,
                           usernames=usernames,
                           category=category,
                           username=session['username'])


@main.route("/notes/<note_id>/")
@login_required
def view_note(note_id):
    """Page to view a specific note"""

    if validate_access_to_note(note_id, session['user_id']):
        note = get_note_by_id(note_id)
        can_edit = (note.user_id == int(session['user_id']))
        return render_template('main/view_note.html', note=note, can_edit=can_edit, username=session['username'])
    else:
        return abort(403)


@main.route('/notes/add', methods=['GET', 'POST'])
@login_required
def add_note():
    """Adding Notes Page"""

    add_note_form = AddNoteForm()

    user_folders = get_folder_names_ids(session['user_id'])
    add_note_form.folder.choices += user_folders

    if add_note_form.validate_on_submit():
        folder_id = int(request.form['folder'])
        title = request.form['title']
        note_markdown = request.form['note']
        private = True if request.form['private'] == 'on' else False

        add_new_note(private, folder_id, title, note_markdown, session['user_id'])
        return redirect(url_for('main.my_notes'))

    return render_template('main/add_notes.html', form=add_note_form, username=session['username'])


@main.route('/notes/edit/<note_id>/', methods=['GET', 'POST'])
@login_required
def edit_note(note_id):
    """Edit note page"""

    edit_note_form = AddNoteForm()

    note = get_note_by_id(note_id)
    if note.user_id != int(session['user_id']):
        return abort(403)

    user_folders = get_folder_names_ids(session['user_id'])
    edit_note_form.private.default = 'on' if note.private else 'off'
    edit_note_form.folder.choices += user_folders
    edit_note_form.folder.default = note.parent_folder_id
    edit_note_form.note.data = note.body
    edit_note_form.title.data = note.title

    if edit_note_form.validate_on_submit():
        folder_id = int(request.form['folder'])
        title = request.form['title']
        note_markdown = request.form['note']
        private = True if request.form['private'] == 'on' else False

        update_note(note_id, private, folder_id, title, note_markdown)
        return redirect(url_for('main.my_notes'))

    return render_template('main/edit_note.html', form=edit_note_form, note_id=note_id, username=session['username'])


@main.route('/notes/delete/<note_id>/')
@login_required
def delete_note(note_id):
    """Delete note page"""

    # You can only delete notes that you create !!
    note = get_note_by_id(note_id)
    if note is None:
        return abort(404)
    elif note.user_id != session['user_id']:
        return abort(403)
    else:
        delete_note_by_id(note_id)
        return my_notes()


@main.route('/profile')
@login_required
def profile():
    """Profile Page"""

    user = get_user_by_id(session['user_id'])
    return render_template('main/profile.html', username=session['username'], user=user)

app/templates/main/add_notes.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        {% for message in form.title.errors %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        {% for message in form.note.errors %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        <form action="{{ url_for("main.add_note") }}" method="POST">
            {{ form.csrf_token }}
            <div class="row" style="padding-top: 2%">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h3 class="card-title"><b>Note Details:</b></h3>
                            <p class="card-text">
                                <h6><b>{{ form.private.label }}</b>{{ form.private }}</h6>
                            </p>
                            <p class="card-text">
                                <h3>{{ form.folder.label }}</h3>
                                <br>
                                {{ form.folder(class='form-control no-borders') }}
                            </p>
                        </div>
                    </div>
                </div> <!-- ./column -->

                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="card mb-8 box-shadow">
                        <div class="card-body">
                            <h3 class="card-title">
                                <b>{{ form.title.label }}</b>
                                {{ form.title(class='form-control no-borders') }}
                            </h3>

                            <p class="card-text">
                                <b>{{ form.note.label }}</b>
                                {{ form.note(class='form-control no-borders') }}
                            </p>
                        </div>
                    </div>
                    {{ form.submit(class='btn btn-primary') }}
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    homelink = document.getElementById("addNote").childNodes[1];
    homelink.className += " active";
</script>

{% endblock %}

app/templates/main/edit_note.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        {% for message in form.title.errors %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        {% for message in form.note.errors %}
            <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}

        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        <form action="{{ url_for("main.edit_note", note_id=note_id) }}" method="POST">
            {{ form.csrf_token }}
            <div class="row" style="padding-top: 2%">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h3 class="card-title"><b>Note Details:</b></h3>
                            <p class="card-text">
                                <h6><b>{{ form.private.label }}</b>{{ form.private }}</h6>
                            </p>
                            <p class="card-text">
                                <h3>{{ form.folder.label }}</h3>
                                <br>
                                {{ form.folder(class='form-control no-borders') }}
                            </p>
                        </div>
                    </div>
                </div> <!-- ./column -->

                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <div class="card mb-8 box-shadow">
                        <div class="card-body">
                            <h3 class="card-title">
                                <b>{{ form.title.label }}</b>
                                {{ form.title(class='form-control no-borders') }}
                            </h3>

                            <p class="card-text">
                                <b>{{ form.note.label }}</b>
                                {{ form.note(class='form-control no-borders') }}
                            </p>
                        </div>
                    </div>
                    {{ form.submit(class='btn btn-primary') }}
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    homelink = document.getElementById("addNote").childNodes[1];
    homelink.className += " active";
</script>

{% endblock %}

app/templates/main/home_page.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        <h1 class="display-4"><i>Cards</i></h1><br>
    </div>
</div>



<script src="{{ url_for('static', filename='js/typed.min.js') }}"></script>
<script>
    homelink = document.getElementById("home").childNodes[1];
    homelink.className += " active";

    function updateClock() {
        var now = new Date(), // current date
        months = ['January', 'February', 'March','April','May','June','July',
                'August','September','October','November','December']; // you get the idea

        // a cleaner way than string concatenation
        date = [now.getDate(),
              months[now.getMonth()],
              now.getFullYear()].join(' ');

        // set the content of the element with the ID time to the formatted string
        document.getElementById('date').innerHTML = date;
    }
    updateClock();
</script>

{% endblock %}

app/templates/main/homepage.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <h1 class="display-4">Welcome back, {{ username }}</h1><br>
    <p class="lead float-right">Date: <span id="date"></span></p>
</div>

<script>
    homelink = document.getElementById("home").childNodes[1];
    homelink.className += " active";

    function updateClock() {
        var now = new Date(), // current date
        months = ['January', 'February', 'March','April','May','June','July',
                'August','September','October','November','December']; // you get the idea

        // a cleaner way than string concatenation
        date = [now.getDate(),
              months[now.getMonth()],
              now.getFullYear()].join(' ');

        // set the content of the element with the ID time to the formatted string
        document.getElementById('date').innerHTML = date;
    }
    updateClock();
</script>

{% endblock %}

app/templates/main/index.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container text-center">
        <h1><i><span class="comments"></span></i></h1><span class="typed-cursor"></span>
        <h4 class="lead"><i> -Mazx</i></h4>
        <p class="lead float-right">Date: <span id="date"></span></p>
    </div>
</div>

<div class="container">
    <div>
        <h2>Features</h2>
    </div>
    <div class="row">
        <div class="col-md-3 col-sm-6">
            <div class="card mb-3 box-shadow h-100">
                <div style="padding-bottom:100%; overflow:hidden; position:relative">
                    <img class="card-img-top"
                         src="{{ url_for('static', filename='images/markdown_icon.jpg') }}"
                         alt="Thumbnail"
                         style="height: 100%; position: absolute">
                </div>
                <div class="card-body">
                    <h4 class="card-title">Markdown</h4>
                    <p class="card-text">
                        With Markdown support, bold, italicize your text all you want
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="card mb-3 box-shadow h-100">
                <div style="padding-bottom:85%; padding-left: 15%; padding-right: 15%; padding-top: 15%; overflow:hidden; position:relative">
                    <img class="card-img-top"
                         src="{{ url_for('static', filename='images/folder_icon.png') }}"
                         alt="Thumbnail"
                         style="height: 70%; width: 70%; position: absolute">
                </div>
                <div class="card-body">
                    <h4 class="card-title">Folders</h4>
                    <p class="card-text">
                        Group your files in folders and keep your work organised
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="card mb-3 box-shadow h-100">
                <div style="padding-bottom:100%; overflow:hidden; position:relative">
                    <img class="card-img-top"
                         src="{{ url_for('static', filename='images/bootstrap_logo.png') }}"
                         alt="Thumbnail" style="height: 100%; position: absolute">
                </div>
                <div class="card-body">
                    <h4 class="card-title">Powerful Frameworks</h4>
                    <p class="card-text">
                        All designed with bootstrap and flask
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-3 col-sm-6">
            <div class="card mb-3 box-shadow h-100">
                <div style="padding-bottom:100%; overflow:hidden; position:relative">
                    <img class="card-img-top"
                         src="{{ url_for('static', filename='images/lock_icon.jpg') }}"
                         alt="Thumbnail" style="height: 100%; position: absolute">
                </div>
                <div class="card-body">
                    <h4 class="card-title">Security</h4>
                    <p class="card-text">
                        Robust security features to ensure that your notes are always safe with us
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='js/typed.min.js') }}"></script>
<script>
    {% if username %}
        homelink = document.getElementById("home").childNodes[1];
        homelink.className += " active";
    {% endif %}

    var comments = new Typed('.comments', {
               strings: ["'The only notes site you'll ever need'",
                         "'Truly Marvellous'",
                         "'Breath-taking'"],
               typeSpeed: 200,
               backSpeed: 100,
               smartBackspace: true, // this is a default
               loop: true,
             });

    function updateClock() {
        var now = new Date(), // current date
        months = ['January', 'February', 'March','April','May','June','July',
                'August','September','October','November','December']; // you get the idea

        // a cleaner way than string concatenation
        date = [now.getDate(),
              months[now.getMonth()],
              now.getFullYear()].join(' ');

        // set the content of the element with the ID time to the formatted string
        document.getElementById('date').innerHTML = date;
    }
    updateClock();
</script>

{% endblock %}

app/templates/main/my_notes.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
    {% if username %}
        {% if delete %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                Note deleted successfully
            </div>
        {% endif %}

        <h1>Welcome, {{ username }}</h1><br>

        <form action="{{ url_for("main.my_notes") }}" method="POST">
            {{ form.csrf_token }}
            <div class="form-row">
                <div class="form-group col-md-9">
                    {{ form.search(class="form-control no_borders", placeholder="Search Note/Users") }}
                </div>
                <div class="form-group col-md-2">
                    {{ form.category(class="form-control no_borders") }}
                </div>
                <input class="form-group col-md-1 btn btn-primary" type="submit" value="Submit">
            </div>
            <input type="submit" style="height: 0; width: 0; border: none; padding: 0;" hidefocus="true">
        </form>

        <div class="panel-group" id="accordion">

            {% for folder_name in folder_names %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#{{ folder_name.replace(' ','_') }}" style="text-decoration: none">
                        <h3>{{ folder_name }}</h3></a>
                    </h4>
                </div>

                <div id="{{ folder_name.replace(' ','_') }}" class="panel-collapse collapse in">
                    <div class="panel-body">
                        {% if notes[folder_name] != [] %}
                            <div class="list-group">
                                {% for note in notes[folder_name] %}
                                    <a href="/notes/{{ note.id }}/" class="list-group-item list-group-item-action flex-column align-items-start">
                                        <div class="d-flex w-100 justify-content-between">
                                            <h4 class="mb-1">{{ note.title }}</h4>
                                            <h6>{{ note.last_edited | datetimeformat }}</h6>
                                        </div>
                                        {% if note.body | length <= 150 %}
                                            <p class="mb-1">{{ note.body }}</p>
                                        {% else %}
                                            <p class="mb-1">{{ note.body[:150] }}...</p>
                                        {% endif %}
                                        <small><i>Made by: {{ usernames[note.user_id] }}</i></small>
                                    </a><br>
                                {% endfor %}
                            </div>
                        {% else %}
                            <div class="alert alert-danger">
                                You have no notes added! Let's add one <a href="/notes/add">here</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    {% endif %}
    </div>
</div>

<script>
    homelink = document.getElementById("notes").childNodes[1];
    homelink.className += " active";
</script>

{% endblock %}

app/templates/main/profile.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
        <h1>General Account settings</h1>
        <hr>
        <table class="table table-hover table-striped table-bordered" style="background-color: ghostwhite;">
            <tr>
                <td>Name</td>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <td>Email</td>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <td>Date joined</td>
                <td>{{ user.date_created | datetimeformat }}</td>
            </tr>
            <tr>
                <td>Last login</td>
                <td>{{ user.last_login | datetimeformat }}</td>
            </tr>
        </table>
    </div>
</div>

<script>
    homelink = document.getElementById("profile").childNodes[1];
    homelink.className += " active";
</script>

{% endblock %}

app/templates/main/search_results.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
    {% if username %}
        {% if delete %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                Note deleted successfully
            </div>
        {% endif %}

        <h1>Your Search Results: </h1><br>

        <form action="{{ url_for("main.my_notes") }}" method="POST">
            {{ form.csrf_token }}
            <div class="form-row">
                <div class="form-group col-md-9">
                    {{ form.search(class="form-control no_borders", placeholder="Search Note/Users") }}
                </div>
                <div class="form-group col-md-2">
                    {{ form.category(class="form-control no_borders") }}
                </div>
                <input class="form-group col-md-1 btn btn-primary" type="submit" value="Submit">
            </div>
            <input type="submit" style="height: 0; width: 0; border: none; padding: 0;">
        </form>

        {% if results != [] %}
            {% if category == 'Notes' %}
                <div class="list-group">
                    {% for note in results %}
                        <a href="/notes/{{ note.id }}/" class="list-group-item list-group-item-action flex-column align-items-start">
                            <div class="d-flex w-100 justify-content-between">
                                <h4 class="mb-1">{{ note.title }}</h4>
                                <h6>{{ note.last_edited | datetimeformat }}</h6>
                            </div>
                            {% if note.body | length <= 150 %}
                                <p class="mb-1">{{ note.body }}</p>
                            {% else %}
                                <p class="mb-1">{{ note.body[:150] }}...</p>
                            {% endif %}
                            <small><i>Made by: {{ usernames[note.user_id] }}</i></small>
                        </a><br>
                    {% endfor %}
                </div>
            {% elif  category == 'Users' %}
                <table class="table table-hover table-striped table-bordered" style="background-color: white;">
                    <thead class="text-center">
                        <tr>
                            <th class="text-center">#</th>
                            <th>Username</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for result in results %}
                            <tr>
                                <td class="text-center">{{ loop.index }}</td>
                                <td>{{ result.username }}</td>
                            </tr>
                        {%  endfor %}
                    </tbody>
                </table>
            {% endif %}
        {% else %}
            <div class="alert alert-danger">
                No results found
            </div>
        {% endif %}
    {% endif %}
    </div>
</div>

<script>
    homelink = document.getElementById("notes").childNodes[1];
    homelink.className += " active";
</script>

{% endblock %}

app/templates/main/today.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container text-center">
        <h1 class="display-4"><i>Welcome back, {{ username }}</i></h1><br>
        <p class="lead float-right">Date: <span id="date"></span></p>
    </div>
</div>



<script src="{{ url_for('static', filename='js/typed.min.js') }}"></script>
<script>
    todaylink = document.getElementById("today").childNodes[1];
    todaylink.className += " active";

    function updateClock() {
        var now = new Date(), // current date
        months = ['January', 'February', 'March','April','May','June','July',
                'August','September','October','November','December']; // you get the idea

        // a cleaner way than string concatenation
        date = [now.getDate(),
              months[now.getMonth()],
              now.getFullYear()].join(' ');

        // set the content of the element with the ID time to the formatted string
        document.getElementById('date').innerHTML = date;
    }
    updateClock();
</script>

{% endblock %}

app/templates/main/view_note.html
{% extends "layout.html" %}

{% block body %}

<div class="jumbotron">
    <div class="container">
    {% if username %}
        <div class="row" style="padding-top: 2%">
            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12">
                <div class="card mb-2 box-shadow">
                    <div class="card-body">
                        <h3 class="card-title"><b>Note Details:</b></h3>
                    </div>
                </div>
            </div> <!-- ./column -->

            <div class="col-lg-10 col-md-10 col-sm-12 col-xs-12">
                <div class="card mb-10 box-shadow">
                    <div class="card-body">
                        <h3 class="card-title"><b>Note Title: </b>{{ note.title }}</h3>
                        <p class="card-text">
                            <small><i>
                                <b>Added on: </b>{{ note.date_created | datetimeformat("%d %b %Y") }}.
                                <b>Last Updated: </b>{{ note.last_edited | datetimeformat("%d %b %Y") }}.
                                {% if note.private %}
                                    *Only you can view this note
                                {% endif %}
                            </i></small>
                        </p>
                        {% if can_edit %}
                            <a href="/notes/edit/{{ note.id }}/" class="pull-left">
                                <button type="button" class="btn btn-info">
                                    <span class="glyphicon glyphicon-edit"></span> Edit
                                </button>
                            </a>
                            <a href="/notes/delete/{{ note.id }}/" class="pull-right">
                                <button type="button" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span> Delete
                                </button>
                            </a>
                        {% endif %}

                        <p class="card-text">
                            {{ note.body_markdown }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    </div>
</div>

<script>
    homelink = document.getElementById("notes").childNodes[1];
    homelink.className += " active";
</script>

{% endblock %}