app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/views/auth.py
"""
Notes Web App
Copyright (C) 2019 DesmondTan
"""


###########
# Imports #
###########

from flask import (
    Blueprint, request, render_template,
    redirect, session, flash
)
from app.utils.forms import LoginForm, SignUpForm
from app.utils.functions import generate_password_hash, datetime
from app.utils.functions import add_new_user, check_user_exist
from app.models import db, User


############
# Settings #
############

bp = Blueprint('auth', __name__)


#########
# Views #
#########

@bp.route('/')
def home_page():
    """Home Page"""

    try:
        if session['username']:
            return render_template('notes/homepage.html', username=session[
                'username'])
        return render_template('notes/homepage.html')
    except (KeyError, ValueError):
        return redirect('/login')


@bp.route('/login/', methods=('GET', 'POST'))
def login():
    """Login Page"""

    login_form = LoginForm()
    if login_form.validate_on_submit():
        username = request.form['username']
        password = (request.form['password'])
        user_id = check_user_exist(username, password)

        if user_id:
            session['username'] = username
            session['user_id'] = user_id
            return redirect('/')
        else:
            flash('Username/Password Incorrect!')
    return render_template('auth/login.html', form=login_form)


@bp.route('/signup/', methods=('GET', 'POST'))
def signup():
    """Sign up page"""

    signup_form = SignUpForm()
    if signup_form.validate_on_submit():
        username = request.form['username']
        password_hash = generate_password_hash(request.form['password'])
        email = request.form['email']
        date_created = datetime.now()
        add_new_user(username, email, password_hash, date_created)

        user_id = check_user_exist(username, password_hash)
        session['username'] = username
        session['user_id'] = user_id

        return redirect('/')

    return render_template('auth/signup.html', form=signup_form)


@bp.route("/logout/")
def logout():
    """Logging out"""

    session['username'] = None
    session['user_id'] = None
    return login()

app/templates/layout.html
<!doctype html>
<html lang="en">
    <head>
        <meta name="viewport" content="width = device-width, initial-scale = 1">
        <meta name="description" content="">
        <meta name="author" content="Desmond Tan">

        <title>Nodes</title>

         <!-- Bootstrap core CSS -->
        <link rel='stylesheet' href="{{ url_for("static", filename="css/bootstrap.min.css") }}">

        <!-- Custom CSS -->
        <style>
            body {
                padding-top: 3.5rem;
            }
        </style>

    </head>
    <body>
        <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
            <div class="container">
                <a class="navbar-brand custom-control-inline" href="{{ url_for('main.index') }}">
                    <h3>
                        <span>
                        <img alt="Icon"
                             style="width: 24px; height: 24px"
                             src="{{ url_for('static', filename='images/nodes_icon.png') }}">
                        Nodes
                        </span>

                    </h3>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavBar" aria-controls="myNavBar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="myNavBar">

                    <ul class="nav nav-pills ml-auto">
                        {% if username %}
                            <li class="nav-item" id="today">
                                <a class="nav-link" href="{{ url_for("main.today") }}">Today</a>
                            </li>
                            <li class="nav-item" id="home">
                                <a class="nav-link" href="{{ url_for("main.home_page") }}">Home</a>
                            </li>
                            <li class="nav-item" id="notes">
                                <a class="nav-link" href="{{ url_for("main.my_notes") }}">My Notes</a>
                            </li>
                            <li class="nav-item" id="addNote">
                                <a class="nav-link" href="{{ url_for("main.add_note") }}">Add Note</a>
                            </li>
                            <li class="nav-item" id="profile">
                                <a class="nav-link" href="{{ url_for("main.profile") }}">View profile</a>
                            </li>
                            <li class="nav-item" id="logout">
                                <a class="nav-link" href="{{ url_for("auth.logout") }}">Log Out</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for("auth.signup") }}"> Sign Up </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for("auth.login") }}"> Login </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>

        <main role="main">
            {% block body %}{% endblock %}
        </main>

        <div style="margin-bottom:5%;"></div>
        <footer class="text-muted">
            <div class="container">
                <hr>
                <p>
                    <img alt="Icon"
                         style="width: 24px; height: 24px"
                         src="{{ url_for('static', filename='images/nodes_icon.png') }}">
                    Nodes v1.0
                </p>
                <p>&copy; Desmond Tan 2019</p>
            </div>
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.4/umd/popper.min.js" integrity="sha512-+Tn2V/oN9O/kiaJg/1o5bETqyS35pMDJzkhkf8uvCzxmRox69AsWkSpBSMEGEe4EZp07Nunw712J3Xvh5Tti0w==" crossorigin="anonymous"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    </body>
</html>